# Using *spotter* for exploring exon-drug associations

In [1]:
import os
import pandas as pd
from target_spotter import SplicingDependency, DrugAssociation

## Load data

In [2]:
# paths
ROOT = os.path.dirname(os.getcwd())
DATA_DIR = os.path.join(ROOT,"data","examples","CCLE")
splicing_file = os.path.join(DATA_DIR, "splicing_EX.tsv.gz")
genexpr_file = os.path.join(DATA_DIR, "genexpr.tsv.gz")

# read
splicing = pd.read_table(splicing_file) # PSI
genexpr = pd.read_table(genexpr_file) # TPM

In [3]:
splicing.head()

,EVENT,ACH-000415,ACH-000894,ACH-000422,ACH-000358,ACH-000468,ACH-000502,ACH-000609,ACH-000636,ACH-000715,...,ACH-000969,ACH-000277,ACH-000036,ACH-000197,ACH-000208,ACH-000359,ACH-000440,ACH-000804,ACH-000174,ACH-000934
0,HsaEX0067681,1.77,1.94,1.18,7.30,0.98,0.00,NaN,8.12,1.67,...,1.75,0.00,0.69,NaN,2.95,3.83,NaN,2.73,2.25,NaN
1,HsaEX6078702,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,...,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.0
2,HsaEX0056692,5.88,38.53,24.35,9.09,16.96,13.33,11.69,1.79,9.63,...,10.30,12.32,17.07,20.83,22.67,36.00,8.36,40.81,18.92,NaN
3,HsaEX0056690,88.89,93.85,83.78,87.65,91.11,94.20,93.33,83.87,78.12,...,86.14,91.26,95.83,NaN,91.30,95.35,94.31,95.40,95.83,NaN
4,HsaEX0056691,100.00,100.00,96.72,100.00,95.24,100.00,100.00,98.78,97.94,...,98.93,99.09,96.96,100.00,100.00,92.52,100.00,100.00,100.00,100.0

In [4]:
genexpr.head()

,ID,ACH-000415,ACH-000894,ACH-000422,ACH-000358,ACH-000468,ACH-000502,ACH-000609,ACH-000636,ACH-000715,...,ACH-000969,ACH-000277,ACH-000036,ACH-000197,ACH-000208,ACH-000359,ACH-000440,ACH-000804,ACH-000174,ACH-000934
0,ENSG00000000003,4.389567,7.281791,5.064366,6.165912,3.939227,3.806324,0.584963,3.720278,3.510962,...,4.479619,1.992768,5.307064,1.144046,4.950935,3.885574,0.632268,5.334497,5.068241,2.625270
1,ENSG00000000005,0.000000,0.014355,0.555816,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.028569,0.000000,0.000000,0.028569,0.000000
2,ENSG00000000419,5.147714,6.803744,6.841596,5.928607,6.625417,7.470537,6.926237,6.569248,6.887647,...,7.334050,8.805421,7.083958,6.962318,6.462380,7.110509,6.588715,7.126291,7.679973,7.010444
3,ENSG00000000457,1.000000,2.469886,2.931683,2.726831,1.963474,2.555816,1.778209,3.303050,2.090853,...,3.145677,3.533563,2.361768,3.553361,2.400538,2.124328,3.943921,3.001802,2.060047,2.833902
4,ENSG00000000460,1.555816,3.811471,3.834913,4.347666,3.228049,2.925999,3.169925,4.613532,2.589763,...,3.270529,3.904002,1.978196,5.164706,3.646163,3.626439,3.816600,4.672425,3.625270,3.538538

## Predict drug sensitivity

### Compute splicing dependency

In [5]:
estimator = SplicingDependency()
spldep_means, max_harm_score_means = estimator.predict(splicing.set_index("EVENT"), genexpr.set_index("ID"))
spldep_means

Loading defaults...
Preprocessing inputs...
Computing splicing dependencies...

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1073/1073 [00:04<00:00, 262.85it/s]

,ACH-000033,ACH-000968,ACH-000889,ACH-000359,ACH-000414,ACH-000957,ACH-000979,ACH-000415,ACH-000277,ACH-000056,...,ACH-000306,ACH-000302,ACH-000969,ACH-000804,ACH-000174,ACH-000663,ACH-000054,ACH-000468,ACH-000502,ACH-000714
HsaEX6065058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.054858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HsaEX6065028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.080116,NaN,NaN,...,NaN,NaN,0.166987,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HsaEX6008208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HsaEX1001338,NaN,-0.063199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.053080,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HsaEX0001886,NaN,NaN,NaN,NaN,NaN,0.071596,NaN,NaN,NaN,NaN,...,0.076398,NaN,0.118040,NaN,NaN,NaN,NaN,NaN,0.077345,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HsaEX0014912,-0.042733,-0.136214,0.007914,-0.075726,-0.033608,-0.007692,0.007651,-0.079462,-0.043506,-0.037989,...,-0.008287,-0.057846,-0.000205,-0.013108,0.010093,0.008867,-0.077286,0.004546,0.025942,-0.089423
HsaEX0073989,NaN,NaN,-0.050063,NaN,NaN,-0.028214,NaN,NaN,-0.021731,NaN,...,NaN,-0.009029,0.034737,-0.023698,-0.041644,NaN,NaN,NaN,NaN,NaN
HsaEX7109159,-0.421889,-0.274199,-0.250018,-0.352082,-0.280428,-0.414230,-0.309202,-0.614516,-0.436812,-0.293094,...,-0.405545,-0.451878,-0.324466,-0.351985,-0.342746,-0.334097,-0.302511,-0.304486,-0.486995,-0.323678
HsaEX7109160,-0.423977,-0.275638,-0.250472,-0.354217,-0.278123,-0.414439,-0.313062,-0.616742,-0.435643,-0.295069,...,-0.405889,-0.456809,-0.324961,-0.346914,-0.335947,-0.335849,-0.301775,-0.305841,-0.498231,-0.307735
HsaEX0043854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compute drug sensitivity

In [6]:
estimator = DrugAssociation()
ic50_by_drug, ic50_by_exon = estimator.predict(spldep_means)

Loading defaults...
Preprocessing inputs...
Estimating drug responses...

In [9]:
ic50_by_drug

             ID      sample  predicted_ic50
0   1001_2000.0  ACH-000033        3.764868
1   1001_2000.0  ACH-000968        3.485597
2   1001_2000.0  ACH-000889        3.422479
3   1001_2000.0  ACH-000359        3.340413
4   1001_2000.0  ACH-000414        3.713157
..          ...         ...             ...
45        9_1.0  ACH-000663       -0.159078
46        9_1.0  ACH-000054       -0.074600
47        9_1.0  ACH-000468       -0.102179
48        9_1.0  ACH-000502       -0.072222
49        9_1.0  ACH-000714       -0.189503

[16000 rows x 3 columns]

In [10]:
ic50_by_exon

,ID,EVENT,ENSEMBL,GENE,ACH-000033,ACH-000968,ACH-000889,ACH-000359,ACH-000414,ACH-000957,...,ACH-000306,ACH-000302,ACH-000969,ACH-000804,ACH-000174,ACH-000663,ACH-000054,ACH-000468,ACH-000502,ACH-000714
0,1_2.0,HsaEX6065058,ENSG00000175899,A2M,NaN,NaN,NaN,NaN,NaN,NaN,...,1.370171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1_2.0,HsaEX6065028,ENSG00000166535,A2ML1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1_2.0,HsaEX6008208,ENSG00000179869,ABCA13,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1_2.0,HsaEX1001338,ENSG00000005471,ABCB4,NaN,2.541271,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1_2.0,HsaEX0001886,ENSG00000159640,ACE,NaN,NaN,NaN,NaN,NaN,3.203030,...,2.479506,NaN,2.633315,NaN,NaN,NaN,NaN,NaN,2.716123,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343355,1530_10.0,HsaEX0014912,ENSG00000153774,CFDP1,3.464704,3.336450,3.465803,3.451162,3.442328,3.629757,...,3.486431,3.455317,3.578291,3.387357,3.525574,3.499735,3.446212,3.543500,3.587548,3.386092
343356,1530_10.0,HsaEX0073989,ENSG00000161551,ZNF577,NaN,NaN,4.452614,NaN,NaN,4.530149,...,NaN,4.378627,4.250901,4.318606,4.469352,NaN,NaN,NaN,NaN,NaN
343357,1530_10.0,HsaEX7109159,ENSG00000239900,ADSL,3.659168,3.674735,3.587498,3.696620,3.625915,3.771126,...,3.629369,3.671943,3.710341,3.538935,3.641976,3.618240,3.694998,3.668921,3.677100,3.652917
343358,1530_10.0,HsaEX7109160,ENSG00000239900,ADSL,3.690423,3.694468,3.605473,3.722389,3.646011,3.801452,...,3.659315,3.705663,3.733845,3.564594,3.666612,3.642749,3.716759,3.691009,3.713899,3.675521
343359,1530_10.0,HsaEX0043854,ENSG00000179915,NRXN1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN