# Using *spotter* for splicing dependency analysis

In [1]:
import os
import pandas as pd
from target_spotter import SplicingDependency

## Load data

In [4]:
# paths
ROOT = os.path.dirname(os.getcwd())
DATA_DIR = os.path.join(ROOT,"data","examples","CCLE")
splicing_file = os.path.join(DATA_DIR, "splicing_EX.tsv.gz")
genexpr_file = os.path.join(DATA_DIR, "genexpr.tsv.gz")

# read
splicing = pd.read_table(splicing_file) # PSI
genexpr = pd.read_table(genexpr_file) # TPM

In [5]:
splicing.head()

,EVENT,ACH-000415,ACH-000894,ACH-000422,ACH-000358,ACH-000468,ACH-000502,ACH-000609,ACH-000636,ACH-000715,...,ACH-000969,ACH-000277,ACH-000036,ACH-000197,ACH-000208,ACH-000359,ACH-000440,ACH-000804,ACH-000174,ACH-000934
0,HsaEX0067681,1.77,1.94,1.18,7.30,0.98,0.00,NaN,8.12,1.67,...,1.75,0.00,0.69,NaN,2.95,3.83,NaN,2.73,2.25,NaN
1,HsaEX6078702,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,...,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.0
2,HsaEX0056692,5.88,38.53,24.35,9.09,16.96,13.33,11.69,1.79,9.63,...,10.30,12.32,17.07,20.83,22.67,36.00,8.36,40.81,18.92,NaN
3,HsaEX0056690,88.89,93.85,83.78,87.65,91.11,94.20,93.33,83.87,78.12,...,86.14,91.26,95.83,NaN,91.30,95.35,94.31,95.40,95.83,NaN
4,HsaEX0056691,100.00,100.00,96.72,100.00,95.24,100.00,100.00,98.78,97.94,...,98.93,99.09,96.96,100.00,100.00,92.52,100.00,100.00,100.00,100.0

In [6]:
genexpr.head()

,ID,ACH-000415,ACH-000894,ACH-000422,ACH-000358,ACH-000468,ACH-000502,ACH-000609,ACH-000636,ACH-000715,...,ACH-000969,ACH-000277,ACH-000036,ACH-000197,ACH-000208,ACH-000359,ACH-000440,ACH-000804,ACH-000174,ACH-000934
0,ENSG00000000003,4.389567,7.281791,5.064366,6.165912,3.939227,3.806324,0.584963,3.720278,3.510962,...,4.479619,1.992768,5.307064,1.144046,4.950935,3.885574,0.632268,5.334497,5.068241,2.625270
1,ENSG00000000005,0.000000,0.014355,0.555816,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.028569,0.000000,0.000000,0.028569,0.000000
2,ENSG00000000419,5.147714,6.803744,6.841596,5.928607,6.625417,7.470537,6.926237,6.569248,6.887647,...,7.334050,8.805421,7.083958,6.962318,6.462380,7.110509,6.588715,7.126291,7.679973,7.010444
3,ENSG00000000457,1.000000,2.469886,2.931683,2.726831,1.963474,2.555816,1.778209,3.303050,2.090853,...,3.145677,3.533563,2.361768,3.553361,2.400538,2.124328,3.943921,3.001802,2.060047,2.833902
4,ENSG00000000460,1.555816,3.811471,3.834913,4.347666,3.228049,2.925999,3.169925,4.613532,2.589763,...,3.270529,3.904002,1.978196,5.164706,3.646163,3.626439,3.816600,4.672425,3.625270,3.538538

## Compute splicing dependency

In [14]:
estimator = SplicingDependency()
spldep_means, max_harm_score_means = estimator.predict(splicing.set_index("EVENT"), genexpr.set_index("ID"))

Loading defaults...
Preprocessing inputs...
Computing splicing dependencies...

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 84/84 [00:00<00:00, 607.29it/s]

In [15]:
spldep_means

,ACH-000302,ACH-000555,ACH-000808,ACH-000359,ACH-000414,ACH-000502,ACH-000968,ACH-000957,ACH-000825,ACH-000609,...,ACH-000655,ACH-000894,ACH-000444,ACH-000230,ACH-000422,ACH-000277,ACH-000636,ACH-000979,ACH-000934,ACH-000080
HsaEX0003833,-0.072373,-0.067266,-0.066096,-0.075082,-0.013102,-0.063606,-0.067781,-0.070601,-0.067673,-0.055344,...,-0.047629,NaN,-0.078659,-0.077367,-0.064659,-0.070817,-0.077791,-0.067372,-0.065893,-0.085661
HsaEX0003834,-0.048514,-0.050018,-0.050363,-0.047716,-0.047236,-0.051096,-0.049866,-0.049036,-0.046533,-0.053530,...,-0.053811,NaN,-0.046663,NaN,-0.050786,-0.048972,-0.046918,-0.049987,NaN,-0.044601
HsaEX1003545,-0.080901,-0.080408,-0.086429,-0.080031,-0.091557,-0.083248,-0.078921,-0.081644,-0.079444,-0.091279,...,-0.103152,-0.058345,-0.075423,-0.074276,-0.088356,-0.076170,-0.069851,-0.086095,-0.080632,-0.062721
HsaEX0004223,0.021837,0.023217,0.038383,0.028687,0.038963,0.056863,0.014283,0.048153,0.047819,0.044698,...,0.044883,0.030835,-0.113868,0.022795,0.053607,0.044061,0.008563,0.061112,0.044578,-0.000050
HsaEX6008957,-0.014398,0.048273,0.035976,0.028806,0.036405,0.049642,0.042903,-0.019120,0.056257,0.058590,...,0.040783,0.030394,0.011863,0.042392,0.047234,0.050385,0.042695,0.052785,0.040557,0.046226

In [16]:
max_harm_score_means

,ACH-000302,ACH-000555,ACH-000359,ACH-000808,ACH-000414,ACH-000502,ACH-000968,ACH-000957,ACH-000825,ACH-000609,...,ACH-000655,ACH-000894,ACH-000444,ACH-000230,ACH-000422,ACH-000277,ACH-000636,ACH-000979,ACH-000934,ACH-000080
HsaEX1015357,-0.076529,-0.179010,0.000000,0.000000,-0.017114,0.000000,-0.161742,-0.042934,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,-0.047017,0.000000,-0.065817,0.000000,0.000000,0.000000
HsaEX6042844,-115.167369,-77.908596,-75.043830,-88.642164,-67.423121,-68.995642,-84.368835,-68.220509,-81.296854,-94.564519,...,-96.396757,-65.795951,-75.443405,-104.116873,-102.961066,-73.283984,-89.933227,-100.135256,-59.919770,-79.786703
HsaEX1028785,-12.384785,-10.054329,-9.730923,-0.014418,-10.126195,-10.771071,-5.964684,-10.268494,-10.237859,-9.987771,...,-10.039696,-10.388067,-10.184897,-0.013052,-11.409845,-11.516838,-10.773555,-9.583822,-8.812217,-10.763188
HsaEX0064661,-1.193184,-3.922649,-0.909088,-2.078326,-2.283953,-8.181166,NaN,-0.707055,-0.000004,-0.034488,...,-1.276340,-2.634897,-1.690868,-4.734772,-0.817443,NaN,-1.799069,-5.522615,NaN,NaN
HsaEX0025717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN